language: python
before_install:
  - pip install pep8
  - pip install pytest-cov
  - pip install python-coveralls
python:
  - "3.6"
script:
 - pep8 --max-line-length=100 __init__.py
after_success:
  coveralls
